title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

url: "https://twiz0311.github.io"
baseurl: "/ACNN-VC"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
